const quoteText = document.querySelector(".quote"),
authorName = document.querySelector(".author .name"),
quoteBtn = document.querySelector("button"),
soundBtn = document.querySelector(".sound"),
copyBtn = document.querySelector(".copy"),
twitterBtn = document.querySelector(".twitter");


   let quotes = 
    [
        'You will receive a lot of Lixi',
        'You will have a lot of money in 2023',
        'You will have a lover',
        'You will meet your true love',
        'You will have a new job',
        'You will see a surprise confess from a person you like',
        'Your ability for accomplishment will follow with success.',
        'Nothing astonishes men so much as common sense and plain dealing.',
        'Everyone agrees. You are the best.',
        'If you feel you are right, stand firmly by your convictions.',
        'A very attractive person has a message for you.',
        'You already know the answer to the questions lingering inside your head.',
        'The man or woman you desire feels the same about you.',
        'If you have something good in your life, dont let it go',
        'Meeting adversity well is the source of your strength.',
        'You learn from your mistakes... You will learn a lot today.',
        'Fortune favors the brave.',
        'Now is the time to try something new.',
        'The man on the top of the mountain did not fall there.',
        'Someone miss you',
        'Your shoes will make you happy today.',
        'There is no greater pleasure than seeing your loved ones prosper.',
        'People are naturally attracted to you.',
        'You will marry your lover.',
        'You cannot love life until you live the life you love.',
        'Heal yourself first then before fallingn in love with someone else',
        'A dream you have will come true.',
        'You learn from your mistakes... You will learn a lot today.',
        'You and your ex will get back together',
        'The love of your life is stepping into your planet this summer.',
        'Love yourself',
        'A stranger, is a friend you have not spoken to yet.',
        'You are very talented in many ways.',
        'Land is always on the mind of a flying bird.',
        'The greatest love is self-love.',
        'What ever you`re goal is in life, embrace it visualize it, and for it will be yours.',
        'Keep your eye out for someone special.',
        'Our deeds determine us, as much as we determine our deeds.',
        'You must try, or hate yourself for not trying.',
        'Be on the lookout for coming events; They cast their shadows beforehand.',
        'You will become great if you believe in yourself.',
        'A very attractive person has a message for you.',
        'A dream you have will come true.',
        'A new voyage will fill your life with untold memories.',
        'Adversity is the parent of virtue.',
        'There is no greater pleasure than seeing your loved ones prosper.',
        'Wealth awaits you very soon.',
        'You will conquer obstacles to achieve success.',
        'If you have something good in your life, dont let it go!',
        'Now is the time to try something new.',
        'Jealousy doesnt open doors, it closes them!',
        'A smile is your passport into the hearts of others.',
        'You will be hungry again in one hour.',
        'Your shoes will make you happy today.',
        'Keep your eye out for someone special.',
        'Enjoy the good luck a companion brings you.',
        'Serious trouble will bypass you.',
        'A short stranger will soon enter your life with blessings to share.',
        'You cannot love life until you live the life you love.',
        'Love can last a lifetime, if you want it to.',
        'A closed mouth gathers no feet.',
        'You can make your own happiness.',
        'Because of your melodic nature, the moonlight never misses an appointment.',
        'You learn from your mistakes... You will learn a lot today.',
        'Somebody appreciates the unique you',
        'Seek out a new enviroment if youre stuck in a rut',
        'We always believe our first love is our last, and our last love our first.',
        'The love of your life is right in front of your eyes.',
        'You have a secret admirer.',
        'The love of your life will appear in front of you unexpectedly!',
        'An old love will come back to you',
        'Your love life will soon be happy and harmonious.',
        'Youre intoxicating when you do what you love.',
        'You should def go for it.',
        'Set yourself up to experience what you love',
        'Self acceptance > self improvement',
        'To be found, stop hiding.',
        '`All you need is love.` - The Beatles',
        'Absence makes the heart grow fonder.',
        'The one you love is closer than you think.',
        'It may be difficult, but it will be worth it in the end.',
        'Stop procrastinating. Make a decision already.',
        'Free your mind, and the rest will follow',
        'Love is right around the corner.',
        'Your hard work will be rewarded',
        'work with what you have',
        'Anxiety won`t help your problems',
        'Don`t hesitate to tackle a difficult problem',
        'Tomorrow is another day',
        'Show everyone what you can do',
        'Pay attention to your family. Don`t take them for granted',
        'Pursue your dreams with vigor',
        'Love is yours if you want it.',
        'If you continually give, you will continually have.',
        'True love doesnt have a happy ending, its because true love doesnt have an ending.',
        'Before you fall in love, make sure there is someone there to catch you.',
        'Your heart is a place to draw true happiness.',
        'Rest has a peaceful effect on your physical and emotional health.',
        'Be the change you want to see in the world',
        'A healthy body will benefit you for life',
        'Fame and fortune lie ahead',
        'Be at peace with yourself',
        'Get ready for a life changing event',
        'An old love will come back to you.',
        'To love and be loved is to feel the sun from both sides.',
        'You will eat a banana',
        'Drink a glass of milk, it`s good for you right now',
        'Stop playing your phone',
        'Comeout and play',
        'You will meet a dog',
        'Eat more s`il vous plait',
        'Hihi nothing for you',
        'I have nothing to say about you',
        'Hard work pays off in the future. Laziness pays off now.',
        'Ninety-nine percent of all lawyers give the rest a bad name.',
        'Delight the world with compassion, kindness and grace.',
        'Patience is your alley at the moment. Don’t worry!',
        'Procrastination is art of keeping up with yesterday.',
        'An alien of some sort will be appearing to you shortly.',
        'You don`t need strength to let go of something. What you really need is understanding.',
        'Don`t eat the paper.',
        'You are cleverly disguised as responsible adult.',
        'If a turtle doesn`t have a shell, is it naked or homeless?',
        'Fat person not afraid of heights _ afraid of widths.',
        'Tension is who you think you should be. Relaxation is who you are.',
        'Stop eating now. Food poisoning no fun.',
        'Some men dream of fortunes, others dream of cookies.',
        'Atheism no fun. No holidays.',
        'If you want the rainbow, you have to tolerate the rain.',
        'A fool and his money are soon partying.',
        'Don`t pursue happiness _ create it.',
        'Nothing is so much to be feared as fear :)) ',
        'Be on the alert to recognize your prime at whatever time of your life it may occur.',
        'Practice safe eating. Always use condiments.',
        'Don`t forget you are always on our minds.',
        'Everyone seems normal until you get to know them.',
        ];
    quoteBtn.addEventListener("click", function(){
        var randomQuote = quotes[Math.floor(Math.random()* quotes.length)]
        quoteText.innerHTML = randomQuote;
    })

soundBtn.addEventListener("click", ()=>{
    // the SpeechSythesisUtterance is a web speech api that represents a speech request
    let utterance = new SpeechSynthesisUtterance(`${quoteText.innerText} }`);
    speechSynthesis.speak(utterance); // speak method of speechSythesis speaks the utterance
});

copyBtn.addEventListener("click", ()=>{
    // copying the quote text on copyBtn click
    // writeText() property writes the specified text string to the system clipboard.
    navigator.clipboard.writeText(quoteText.innerText)
});

twitterBtn.addEventListener("click", ()=>{
    let tweetUrl = `https://twitter.com/intent/tweet?url=${quoteText.innerText}`;
    window.open(tweetUrl,"_blank"); // opening a new twitter tab with passing quote in the url
});

